modLoader = "javafml"
loaderVersion = "[46,)"
issueTrackerURL = "https://github.com/DialingSpoon527/Partial-Hearts/issues"
license = "MIT"

[[mods]]
modId = "partialhearts"
version = "${version}"
displayName = "Partial Hearts"
authors = "DialingSpoon"
description = '''
Exact health displayed with fractions of a heart.
'''
logoFile = "assets/partialhearts/icon.png"

[[dependencies.partialhearts]]
modId = "forge"
mandatory = true
versionRange = "(47,49)"
ordering = "NONE"
side = "BOTH"

[[dependencies.partialhearts]]
modId = "minecraft"
mandatory = true
versionRange = "(1.20.1,1.20.3)"
ordering = "NONE"
side = "BOTH"