modLoader = "javafml"
loaderVersion = "[47,)"
issueTrackerURL = "https://github.com/19Phin/Partial-Hearts/issues"
license = "MIT"

[[mods]]
modId = "partialhearts"
version = "${version}"
displayName = "Partial Hearts"
authors = "DialingSpoon"
description = '''
Exact health displayed with fractions of a heart.
'''
logoFile = "assets/partialhearts/icon.png"

[[dependencies.partialhearts]]
modId = "forge"
mandatory = true
versionRange = "(46,48)"
ordering = "NONE"
side = "BOTH"

[[dependencies.partialhearts]]
modId = "minecraft"
mandatory = true
versionRange = "(1.20,1.20.2)"
ordering = "NONE"
side = "BOTH"