modLoader = "javafml"
loaderVersion = "[1,)"
issueTrackerURL = "https://github.com/DialingSpoon527/Partial-Hearts/issues"
license = "MIT"

[[mods]]
modId = "partialhearts"
version = "${version}"
displayName = "Partial Hearts"
authors = "DialingSpoon"
description = '''
Exact health displayed with fractions of a heart.
'''
logoFile = "icon.png"

[[dependencies.partialhearts]]
modId = "neoforge"
mandatory = true
versionRange = "(20.2,20.5)"
ordering = "NONE"
side = "BOTH"

[[dependencies.partialhearts]]
modId = "minecraft"
mandatory = true
versionRange = "(1.20.2,1.20.5)"
ordering = "NONE"
side = "BOTH"

[[mixins]]
config = "partialhearts.mixins.json"
[[mixins]]
config = "partialhearts.neo.mixins.json"