modLoader = "javafml"
loaderVersion = "[1,)"
issueTrackerURL = "https://github.com/DialingSpoon527/Partial-Hearts/issues"
license = "MIT"

[[mods]]
modId = "partialhearts"
version = "${version}"
displayName = "Partial Hearts"
authors = "DialingSpoon"
description = '''
Exact health displayed with fractions of a heart.
'''
logoFile = "assets/partialhearts/icon.png"

[[dependencies.partialhearts]]
modId = "neoforge"
type = "required"
versionRange = "(21.8,)"
ordering = "NONE"
side = "BOTH"

[[dependencies.partialhearts]]
modId = "minecraft"
type = "required"
versionRange = "(1.21.8,)"
ordering = "NONE"
side = "BOTH"

[[mixins]]
config = "partialhearts.mixins.json"
[[mixins]]
config = "partialhearts.neo.mixins.json"